### ISSUE TITLE
UI styling

### ISSUE THREAD

**Issue by kraftwer1** [rokoroku/vscode-theme-darcula#6]
Annyeong-haseyo

I've created a new theme based on your great work. The main difference is that mine is also styling UI elements, since that's now supported. I first wanted to create a pull request, but the differences were too big (XML => JSON). But if you don't mind these changes, we could still merge?

https://github.com/kraftwer1/vscode-theme-darcula-extra

**Comment by rokoroku** [comment]
I can see a lot of broken rules with your configurations, so it's hard to merge your work now.

If you only add **ui-stylings attributes** without changing any existing rules, I can accept your work in this extension. 
And it will be added as different theme entry like the screenshot since it's not written in **tmTheme** format.

Anyway, thanks for your interest :) 

![2017-05-15 10 58 25](https://cloud.githubusercontent.com/assets/5208632/26040141/8598cae2-395d-11e7-9d1a-f9993ebe6efb.png)
![2017-05-15 10 58 29](https://cloud.githubusercontent.com/assets/5208632/26040142/8599eac6-395d-11e7-80b4-093dfc210743.png)

**Comment by rokoroku** [comment]
Maybe I can write a theme generator for both `vscode` & `tmTheme` later.

**Comment by kraftwer1** [comment]
With "broken rules" you mean selectors like "punctuation.meta.something"? How do you check these?

**Comment by rokoroku** [comment]
Use vscode's **tmScope inspector** ( open palette and search `Developer: Inspect TM Scopes` )

**Comment by kraftwer1** [comment]
Thanks, and in what way are they broken?

**Comment by rokoroku** [comment]
Some UI styling has been updated in v1.1.0, closed
